language: python
python:
- '3.5'
install:
- pip install -r requirements.txt
- python manage.py makemigrations
- python manage.py migrate
script:
- pytest
branches:
  only:
    - master
deploy:
  provider: heroku
  app: mysterious-thicket-84893
  api_key:
    secure: KeK0pd11ouE1NX/hYHC3efwCwYxOSC5ACJH+c07cyGGzPzWbYvB0AVskSoWkfyp6bXS3sn+IXoYZvP2XMXdBWoc0yPSIxo1uLVXDiYfb3j8IewI26yXnSQjxK4W1bFU1w2JKO8CnN7DnlPfP3/dxW0GPUUlAE7VQGnyKaQH84++jqj1JITJAfZgoAK6x8Zgg30SH1DSCKZN/3FK4HA/5VQN+ektjHoneW5ZwvjVc9M7I3YPZX6J0ddvqvEfxfNIrx6rgBWxHuj2cARnd91eykLZ8z4gB54lf5gybgkDU0dRqOdq17Nf7uCiCfqykw+FPSb1HQIUbRiDw7PslxGxQ0F+SelEV0VcAI0hxlKWgh9vuoI9am9LqDHBWsJcV1qulYtxxVZpDNnf/7rE/za9nuygVienxiKzxo190I9Urs0vuADXfXEZV0uovv29/dUu5fYN5bsWJSCmA9xoeC/0Qjv4aiS1XbXXxzYWio+rBUzNf8s+kGRAidEg4KBdUl28tpDAKmPXGYuIKpVrXEQ61WJx6e4b4Cx25HmPYUXWpgChyYlO5SLNpkL3aiv/Q0odZ9ouAu8tXtHfaFICy1HZIxiFWC16o6T52lNwekSLt01r/hF7bPW09/E48AOTwKEUJH/4x14nHafJeoU0YG405qAqtmuIYiTBPPxRZg6fc/zA=
notifications:
  slack:
    secure: oc6p0ev4CLddmTc4n3QEnH6tbaj8wLVXGTxmLUat/1ZwH67OS2M4sMcDtI8ZgrMjwY4HxWV6H29Fhiox/0+sdL+AV6sF8l1L4uoEuM6HhxZHYt4JpG8O3SQkr3JQRafrLDUATH1AOjFpjssGcl7eHQPEZJ15mICwNRQRvvcgriQamzoZXrAPEWbvGWN4ejQecckCAYrTRqVGTrZVwpE+1TF1JMte+wJxqZDwxzEavPjJXPNBAgpXxo++bUNHCGzWsvIpnkdtt2n3Qm+dvRRKxxpkxK5/L8Fn6rEgEh3L/HsJKvxonTCP5eFxO3I2jwM0jWkBPHwWeS54SLCeiuC4J/uHO4qQJwSghr0nVvx4367GKA9azixPKm8BhIGVgByX3AXC2NZlNW5FV6K5VfA4nlC0JwlNrBnMDcoc7kGGBEdZGCkCd4P7ljvpO2Q2PHIyahUFPsodhaFT2PvN/8zp5qv5bXZ/Qqyy+vgToXVP+K1YSOr/nbAbrLNqr3ojWNRaEwqrFw1kDcWm6nIn2FonoPh8Rb0qJ1qT0ZJ4O1JnSPCN2n+zpA69xAH3aLsoqM6SAT7PsWr3l6DgLxV4WMjYtm5CNpa5iUfWusGFVsWF77zFkU1Rv3zRAmR59q6xRpeH+G0vVfhpOSzwnIGM6YinzFMnxvv2LqwNqIVvejBceJM=
